antonino_simple_emailer_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AntoninoSimpleEmailerBundle:Default:index }

antonino_template_design:
    pattern: /global-template
    defaults: { _controller: AntoninoSimpleEmailerBundle:Default:globalTemplate }

antonino_emailer:
    pattern: /email/{emailAddress}
    defaults: { _controller: AntoninoSimpleEmailerBundle:Default:email}

antonino_email_into_db:
    pattern: /email/{emailAddress}
    defaults: { _controller: AntoninoSimpleEmailerBundle:Default:insertIntoDB}